### ISSUE TITLE
The graph moves at surprising and random moments

### ISSUE THREAD

**Issue by jbon** [jbon/design-dependencies#1]
Reproduce (does not always work): 
- Start with an empty graph
- Add two nodes and connect them
- Click anywhere on the background
- The graph “jumps”
- Click on physical
- Click anywhere on the background
- The nodes change their positions

It seems there are two modes according to which the graph behaves
- At the beginning it is dynamic: the nodes are “floating” and moving independently and the layout is constantly recalculated 
- Once you click on “physical” or “hierarchic”, the layout becomes static and does not move independently anymore

**Comment by jbon** [comment]
Also: Node move does not systematically work: after a move, a right click in the background will make the node come back. This behaviour is quite random, though. Don’t know how to reproduce.

**Comment by adumascrouzillac** [comment]
bug fixed. I'm waiting for the meeting to close the issue.
