### ISSUE TITLE
Node remove does not work

### ISSUE THREAD

**Issue by jbon** [jbon/design-dependencies#3]
It is deleted from the graph for a short time but reappears when the graph is redrawn. It seems the node is not deleted from the nodeDataSet.

**Comment by jbon** [comment]
I tried a workaround which does not work: When you delete an item manually in the input JS file, it creates a gap in the series of node ids. Then you get an error next time you try to create a node "Uncaught Error: Cannot add item: item with id <number> already exists"

**Comment by adumascrouzillac** [comment]
Bug fixed with the right click menu. We still have to fix it on the "Delete Selected" button.
